export const KANBAN_COLUMNS = [
  {
    id: 'READY_FOR_DISPATCH',
    label: 'Ready for Dispatch',
    code: 'STG-01',
    accentColor: 'border-blue-500',
    tagColor: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    dotColor: 'bg-blue-500',
    description: 'Order picked & packed, awaiting courier allocation',
  },
  {
    id: 'ASSIGNED',
    label: 'Courier Allocated',
    code: 'STG-02',
    accentColor: 'border-indigo-500',
    tagColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30',
    dotColor: 'bg-indigo-500',
    description: 'Courier assigned, awaiting hub pickup confirmation',
  },
  {
    id: 'PICKED_UP',
    label: 'Hub Departure',
    code: 'STG-03',
    accentColor: 'border-amber-500',
    tagColor: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    dotColor: 'bg-amber-500',
    description: 'Package in courier possession, staging for transit',
  },
  {
    id: 'IN_TRANSIT',
    label: 'Active Road Transit',
    code: 'STG-04',
    accentColor: 'border-cyan-500',
    tagColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    dotColor: 'bg-cyan-500',
    description: 'En route to recipient destination address',
  },
  {
    id: 'DELIVERED',
    label: 'Delivered (POD)',
    code: 'STG-05',
    accentColor: 'border-emerald-500',
    tagColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    dotColor: 'bg-emerald-500',
    description: 'Recipient verified, proof of delivery logged',
  },
];
